// Regenerates src/lib/components/Icon.svelte from the remixicon package.
//
// Why inline instead of the Remix Icon font: the site is prerendered and ships
// zero third party requests at runtime, and an icon font would add ~100KB plus a
// flash of unstyled icons. Copying the path data in keeps that property.
//
// Remix Icon is Apache-2.0; the licence text stays in node_modules/remixicon/License
// and the attribution lives in the generated component and the README.
//
// Usage: node scripts/build-icons.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const ICON_DIR = join(ROOT, 'node_modules/remixicon/icons');

// name in <Icon name="..."> -> path inside the remixicon package (no extension)
const ICONS = {
	// download buttons
	pdf: 'Document/file-pdf-2-line',
	word: 'Document/file-word-2-line',
	// contact rows
	mail: 'Business/mail-line',
	phone: 'Device/phone-line',
	linkedin: 'Logos/linkedin-box-line',
	pin: 'Map/map-pin-line',
	// section headings
	user: 'User & Faces/user-line',
	work: 'Business/window-2-line',
	briefcase: 'Business/briefcase-line',
	code: 'Development/code-s-slash-line',
	cert: 'Document/certificate-2-line',
	chat: 'Communication/chat-3-line',
	// hero spec rows
	focus: 'Design/focus-3-line',
	stack: 'Business/stack-line',
	// rail chips
	home: 'Buildings/home-line',
	// row labels: working style, skills groups, education
	calendar: 'Business/calendar-line',
	building: 'Buildings/building-2-line',
	database: 'Device/database-2-line',
	server: 'Device/server-line',
	layout: 'Design/layout-line',
	flow: 'Editor/flow-chart',
	shield: 'System/shield-check-line',
	team: 'User & Faces/team-line',
	book: 'Document/book-2-line',
	translate: 'Editor/translate-2',
	sparkle: 'Weather/sparkling-2-line',
	compass: 'Map/compass-3-line',
	graduation: 'Others/graduation-cap-line',
	award: 'Business/award-line'
};

const { version } = JSON.parse(readFileSync(join(ROOT, 'node_modules/remixicon/package.json'), 'utf8'));

const entries = Object.entries(ICONS).map(([name, path]) => {
	const svg = readFileSync(join(ICON_DIR, `${path}.svg`), 'utf8');
	const inner = svg
		.replace(/^[\s\S]*?<svg[^>]*>/, '')
		.replace(/<\/svg>\s*$/, '')
		.trim();
	if (!inner.startsWith('<path')) throw new Error(`unexpected markup for ${name}: ${inner.slice(0, 40)}`);
	return `\t\t${name}: '${inner.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
});

const file = `<script lang="ts">
	/**
	 * Inline icon set. Path data: Remix Icon v${version}, Apache-2.0.
	 * Generated by scripts/build-icons.mjs, do not edit by hand.
	 */
	const ICONS: Record<string, string> = {
${entries.join(',\n')}
	};

	let { name, size = 16 }: { name: string; size?: number } = $props();
	const paths = $derived(ICONS[name] ?? '');
</script>

{#if paths}
	<svg
		viewBox="0 0 24 24"
		fill="currentColor"
		width={size}
		height={size}
		aria-hidden="true"
		focusable="false"
	>
		{@html paths}
	</svg>
{/if}
`;

writeFileSync(join(ROOT, 'src/lib/components/Icon.svelte'), file);
console.log(`wrote src/lib/components/Icon.svelte with ${entries.length} icons (remixicon ${version})`);
