<script lang="ts">
	import Backdrop from './Backdrop.svelte';
	import ArchitectureMap from './ArchitectureMap.svelte';
	import { facts, profile, ui } from '$lib/content/site';
</script>

<section class="hero" id="top">
	<Backdrop />

	<div class="wrap hero-inner">
		<div>
			<p class="eyebrow">{profile.eyebrow}</p>
			<!-- The R of the name IS the site mark (static/icon/mark-*, generated by
			     scripts/make-mark-icons.py). Both files are in the DOM and [data-theme]
			     shows one, so the right colour is painted before first paint with no
			     javascript involved. The h1 is labelled, so assistive tech still reads
			     the full name.
			     TRAP: whitespace between inline elements is a real word space (~15px at
			     68px type). The .mark-slot wrapper carries font-size: 0 so every
			     whitespace run inside it is zero-width and the name cannot drift away
			     from the mark, however this file is reformatted. scripts/check-icons.py
			     fails if the slot or the zero font size goes missing. -->
			<h1 aria-label={profile.name}>
				<span class="mark-slot">
					<img
						class="mark mark-dark"
						src="/icon/mark-dark.png"
						alt=""
						aria-hidden="true"
						width="384"
						height="384"
						loading="lazy"
						decoding="async"
					/>
					<img
						class="mark mark-light"
						src="/icon/mark-light.png"
						alt=""
						aria-hidden="true"
						width="384"
						height="384"
						loading="lazy"
						decoding="async"
					/>
					<span class="name" aria-hidden="true">{profile.name.slice(1)}</span>
				</span>
			</h1>
			<p class="role">{profile.role}</p>
			<p class="pitch">{profile.pitch}</p>

			<div class="cta-row">
				<a class="btn primary" href="#work">
					{ui.hero.seeWork}
					<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
						<path d="M5 12h14M13 6l6 6-6 6" />
					</svg>
				</a>
				<a class="btn" href="#contact">{ui.hero.contactMe}</a>
			</div>
		</div>

		<div class="spec">
			<div class="spec-bar" aria-hidden="true">
				<span class="dot"></span>
				<span class="dot"></span>
				<span class="dot"></span>
				<span class="spec-file">spec.yml</span>
			</div>

			<div class="spec-body">
				<p class="spec-line" aria-hidden="true">
					rithea@sreng<span class="dim">:~/portfolio$</span> cat spec.yml
				</p>

				<dl class="spec-rows" aria-label={ui.hero.atAGlance}>
					{#each facts as fact (fact.label)}
						<div class="spec-row">
							<dt>{fact.label.toLowerCase().replaceAll(' ', '_')}</dt>
							<dd><span class="eq" aria-hidden="true">=</span>{fact.value}</dd>
						</div>
					{/each}
				</dl>

				<div class="arch">
					<p class="spec-line" aria-hidden="true">
						rithea@sreng<span class="dim">:~/portfolio$</span> cat architecture.svg
					</p>
					<ArchitectureMap />
				</div>

				<p class="spec-cursor" aria-hidden="true"><span class="caret"></span></p>
			</div>
		</div>
	</div>
</section>
